parameters:
  tf_working_dir: ""
  tf_rg: ""
  tf_storage: ""
  tf_container: ""
  tfstateKey: ""
  sc_name: ""

jobs:
- job: validatePlan
  steps:
    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: azurerm
        command: init
        workingDirectory: ${{ parameters.tf_working_dir }}
        backendServiceArm: ${{ parameters.sc_name }}
        backendAzureRmResourceGroupName: ${{ parameters.tf_rg }}
        backendAzureRmStorageAccountName: ${{ parameters.tf_storage }}
        backendAzureRmContainerName: ${{ parameters.tf_container }}
        backendAzureRmKey: ${{ parameters.tfstateKey }}

    - task: TerraformTask@5
      displayName: "Terraform Validate"
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: ${{ parameters.tf_working_dir }}

    - task: TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: ${{ parameters.tf_working_dir }}
        environmentServiceNameAzureRM: ${{ parameters.sc_name }}
