parameters:
  tf_working_dir: ""
  tf_rg: ""
  tf_storage: ""
  tf_container: ""
  tfstateKey: ""
  sc_name: ""

jobs:
- job: terraformInstall
  steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: ${{ parameters.tf_working_dir }}
        backendServiceArm: ${{ parameters.sc_name }}
        backendAzureRmResourceGroupName: ${{ parameters.tf_rg }}
        backendAzureRmStorageAccountName: ${{ parameters.tf_storage }}
        backendAzureRmContainerName: ${{ parameters.tf_container }}
        backendAzureRmKey: ${{ parameters.tfstateKey }}

    - task: TerraformTask@5
      displayName: "Terraform fmt"
      inputs:
        provider: 'azurerm'
        command: 'custom'
        workingDirectory: ${{ parameters.tf_working_dir }}
        customCommand: 'fmt'
